### ISSUE TITLE
Can't locate the app file

### ISSUE THREAD

**Issue by raulbehl** [rajatkapoor/movieapp#1]
Hi, 

I wanted to try out the App on my phone but couldn't locate any file which I could load. Is the repo up-to-date?

Thank you!

**Comment by rajatkapoor** [comment]
Hi @raulbehl ,
Thanks for your interest in this repo.
I have commited all my progress in the repo now. You can pull no to get the update. Do let me know if you need any help setting things up (I am yet to add a proper `README`)

**Comment by raulbehl** [comment]
Great. Thanks!
